import axios from "axios";
import dotenv from "dotenv";
import mongoose from "mongoose";
import { User } from "./models/user.model.js";

dotenv.config();
const baseURL = "http://localhost:7000/api/v1";
const client = axios.create({ baseURL, withCredentials: true, validateStatus: () => true });
const email = process.argv[2];
const password = process.argv[3];
console.log('EMAIL', email);
const register = await client.post('/user/register-user', { username: 'CopilotSmoke', email, password }).catch(e => e.response || e);
console.log('register', register.status, JSON.stringify(register.data));
const login = await client.post('/user/login', { email, password }).catch(e => e.response || e);
console.log('login', login.status, JSON.stringify(login.data));
const cookie = login.headers?.['set-cookie']?.map(c => c.split(';')[0]).join('; ') || '';
console.log('cookie', cookie ? 'present' : 'missing');
const authClient = axios.create({ baseURL, headers: { Cookie: cookie }, validateStatus: () => true });
const current = await authClient.get('/user/current-user').catch(e => e.response || e);
console.log('current-user', current.status, JSON.stringify(current.data));
const createTicket = await authClient.post('/tickets/create-ticket', { title: 'Smoke ticket', description: 'Smoke test ticket', priority: 'high' }).catch(e => e.response || e);
console.log('create-ticket', createTicket.status, JSON.stringify(createTicket.data));
const ticketId = createTicket.data?.data?._id;
if (!ticketId) {
  console.error('No ticket created; aborting.');
  process.exit(1);
}
const getTicket = await authClient.get(`/tickets/${ticketId}`).catch(e => e.response || e);
console.log('get-ticket', getTicket.status, JSON.stringify(getTicket.data));
const myTickets = await authClient.get('/tickets/my-tickets').catch(e => e.response || e);
console.log('my-tickets', myTickets.status, JSON.stringify(myTickets.data));
const addComment = await authClient.post(`/comments/ticket/${ticketId}`, { message: 'Smoke comment' }).catch(e => e.response || e);
console.log('add-comment', addComment.status, JSON.stringify(addComment.data));
const comments = await authClient.get(`/comments/ticket/${ticketId}`).catch(e => e.response || e);
console.log('get-comments', comments.status, JSON.stringify(comments.data));
await mongoose.connect(process.env.DATABSE_URL);
const adminUser = await User.findOneAndUpdate({ email }, { role: 'admin' }, { new: true });
console.log('promoted-admin', adminUser?.role || 'none');
await mongoose.disconnect();
const assign = await authClient.patch(`/tickets/${ticketId}/assign`, { assignedToEmail: email }).catch(e => e.response || e);
console.log('assign', assign.status, JSON.stringify(assign.data));
const status = await authClient.patch(`/tickets/${ticketId}/status`, { status: 'resolved' }).catch(e => e.response || e);
console.log('status', status.status, JSON.stringify(status.data));
const ticketFinal = await authClient.get(`/tickets/${ticketId}`).catch(e => e.response || e);
console.log('ticket-final', ticketFinal.status, JSON.stringify(ticketFinal.data));
const allTickets = await authClient.get('/tickets/all').catch(e => e.response || e);
console.log('all-tickets', allTickets.status, JSON.stringify(allTickets.data));
const allUsers = await authClient.get('/user/admin/users').catch(e => e.response || e);
console.log('admin-users', allUsers.status, JSON.stringify(allUsers.data));
